# Generated by Django 3.1.6 on 2021-02-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0002_auto_20210208_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='county',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='competitor',
            name='school',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
