# Generated by Django 3.1.6 on 2021-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0004_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='isEven',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
