# Generated by Django 3.1.6 on 2021-02-19 17:20

from django.db import migrations, models
import django.db.models.deletion
import innovate.models


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0005_judge_iseven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation', innovate.models.IntegerRangeField()),
                ('need', innovate.models.IntegerRangeField()),
                ('finances', innovate.models.IntegerRangeField()),
                ('creativity', innovate.models.IntegerRangeField()),
                ('qna', innovate.models.IntegerRangeField()),
                ('speaking', innovate.models.IntegerRangeField()),
                ('persuasiveness', innovate.models.IntegerRangeField()),
                ('professionalism', innovate.models.IntegerRangeField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovate.judge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovate.team')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
